variable "aws_region" {
  description = "AWS region where the Lambda infrastructure will be created."
  type        = string
  default     = "us-east-1"
}

variable "skip_aws_credentials_validation" {
  description = "Skip AWS credential validation during local and pull request plans."
  type        = bool
  default     = true
}

variable "skip_aws_metadata_api_check" {
  description = "Skip AWS metadata API checks during local and pull request plans."
  type        = bool
  default     = true
}

variable "skip_aws_requesting_account_id" {
  description = "Skip AWS account ID lookup during local and pull request plans."
  type        = bool
  default     = true
}

variable "project_name" {
  description = "Project name used as a prefix for AWS resources."
  type        = string
  default     = "oficina-dgcar"
}

variable "environment" {
  description = "Environment name for tagging and naming."
  type        = string
  default     = "homolog"
}

variable "lambda_package_path" {
  description = "Path to the Lambda zip package generated by npm run package."
  type        = string
  default     = "../dist/auth-cpf-lambda.zip"
}

variable "lambda_timeout_seconds" {
  description = "Lambda timeout in seconds."
  type        = number
  default     = 10
}

variable "lambda_memory_size_mb" {
  description = "Lambda memory size in MB."
  type        = number
  default     = 256
}

variable "log_retention_days" {
  description = "CloudWatch log retention in days."
  type        = number
  default     = 14
}

variable "vpc_id" {
  description = "VPC ID that allows Lambda connectivity to RDS."
  type        = string
  default     = "vpc-12345678"
}

variable "subnet_ids" {
  description = "Private subnet IDs used by Lambda."
  type        = list(string)
  default     = ["subnet-12345678", "subnet-87654321"]
}

variable "additional_security_group_ids" {
  description = "Additional security group IDs attached to the Lambda."
  type        = list(string)
  default     = []
}

variable "db_host" {
  description = "RDS PostgreSQL endpoint."
  type        = string
  default     = "localhost"
}

variable "db_port" {
  description = "RDS PostgreSQL port."
  type        = string
  default     = "5432"
}

variable "db_name" {
  description = "PostgreSQL database name."
  type        = string
  default     = "oficina"
}

variable "db_username" {
  description = "PostgreSQL database username."
  type        = string
  default     = "oficina"
}

variable "db_password" {
  description = "PostgreSQL database password."
  type        = string
  sensitive   = true
  default     = "change-me"
}

variable "db_ssl" {
  description = "Whether the Lambda should use SSL to connect to PostgreSQL."
  type        = string
  default     = "false"
}

variable "client_table" {
  description = "Client table name."
  type        = string
  default     = "clientes"
}

variable "client_id_column" {
  description = "Client ID column name."
  type        = string
  default     = "id"
}

variable "client_document_column" {
  description = "Client document column name."
  type        = string
  default     = "documento"
}

variable "client_password_hash_column" {
  description = "Client password hash column name."
  type        = string
  default     = "senha_hash"
}

variable "client_status_column" {
  description = "Client status column name. Keep empty until status_cliente exists."
  type        = string
  default     = ""
}

variable "client_default_status" {
  description = "Default status used when client_status_column is empty."
  type        = string
  default     = "ATIVO"
}

variable "client_allowed_statuses" {
  description = "Comma-separated list of statuses allowed to authenticate."
  type        = string
  default     = "ATIVO"
}

variable "client_jwt_secret" {
  description = "Secret used to sign external client JWTs."
  type        = string
  sensitive   = true
  default     = "change-me-with-at-least-32-characters"
}

variable "client_jwt_issuer" {
  description = "JWT issuer."
  type        = string
  default     = "oficina-dgcar-auth-lambda"
}

variable "client_jwt_audience" {
  description = "JWT audience."
  type        = string
  default     = "oficina-dgcar-api"
}

variable "client_jwt_expires_in" {
  description = "JWT expiration duration."
  type        = string
  default     = "15m"
}
